name: cd

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd BPS-WA-Chatbot
            git pull origin main
            git status

            # Ensure NVM is loaded
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Use the correct Node.js version
            nvm use 20.15.1

            # Create symlinks if they don't exist
            sudo ln -sf "$(which node)" "/usr/local/bin/node"
            sudo ln -sf "$(which npm)" "/usr/local/bin/npm"

            # Install PM2 globally if not already installed
            npm list -g | grep pm2 || npm install -g pm2

            # Create PM2 symlink
            sudo ln -sf "$(which pm2)" "/usr/local/bin/pm2"

            # Reload and restart your application
            pm2 reload BPS
            pm2 restart BPS
